remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: AutoLead
description: Our AI-powered chatbot is designed to help dealerships capture leads, answer questions, and assist customers in finding their perfect vehicle. From scheduling test drives to providing detailed inventory insights, the chatbot works seamlessly to enhance your website's customer engagement.
